# Generated by Django 2.2.5 on 2019-09-07 13:52

from django.conf import settings
from django.db import migrations, models
import posts.models
import posts.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscribers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=posts.models.upload_location, validators=[posts.validators.validate_file_extensions]),
        ),
    ]
