# Generated by Django 2.2.5 on 2019-09-08 12:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20190907_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscribed_for', to=settings.AUTH_USER_MODEL),
        ),
    ]
