version: "3"

services:
  djangoapp:
    ports:
      - "8000:8000" # we'll use port 5000 for django
    environment:
      - DJANGO_ENV=development
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=planeks-news
      - POSTGRES_PORT=5432

  db:
    ports:
      - "5435:5432"  # pointing port 5435 from our environment to postgre default port 5432 in docker
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'planeks_news'
      POSTGRES_PORT: 5432
