version: "3"

services:
  djangoapp:
    ports:
      - "8000:8000"
    environment:
      - DJANGO_ENV=production
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=planeks_news
      - POSTGRES_PORT=5432

  db:
    ports:
      - "5435:5432"
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_DB: 'planeks_news'
      POSTGRES_PORT: 5432
